// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const normalizeSupabaseUrl = (rawUrl?: string, projectId?: string) => {
  const cleaned = (rawUrl || '').trim().replace(/^['"]|['"]$/g, '');
  if (cleaned.startsWith('http://') || cleaned.startsWith('https://')) {
    return cleaned;
  }
  if (cleaned) {
    return `https://${cleaned.replace(/^https?:\/\//, '')}`;
  }
  if (projectId) {
    return `https://${projectId}.supabase.co`;
  }
  return 'https://placeholder.supabase.co';
};

const SUPABASE_URL = normalizeSupabaseUrl(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_PROJECT_ID
);
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '').trim().replace(/^['"]|['"]$/g, '') ||
  (import.meta.env.VITE_SUPABASE_ANON_KEY || '').trim().replace(/^['"]|['"]$/g, '') ||
  'placeholder';
const isPlaceholderUrl = SUPABASE_URL.includes('placeholder.supabase.co');
const hasCredentials = SUPABASE_PUBLISHABLE_KEY !== 'placeholder';

export const SUPABASE_RUNTIME_INFO = {
  url: SUPABASE_URL,
  hasProjectId: Boolean(import.meta.env.VITE_SUPABASE_PROJECT_ID),
  hasUrl: Boolean(import.meta.env.VITE_SUPABASE_URL),
  hasPublishableKey: Boolean(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY),
  hasAnonKey: Boolean(import.meta.env.VITE_SUPABASE_ANON_KEY),
  isConfigured: !isPlaceholderUrl && hasCredentials,
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
